config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "todos#index"
  resources :todos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
    validates_presence_of :title, :description
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
    before_action :set_todo, only: [:edit, :show, :destroy, :update]

    def index
        @todo = Todo.all
    end

    def new
        @todo = Todo.new
    end

    def create
        @todo = Todo.new(todo_params)
        respond_to do |format|
            if @todo.save
                format.html {redirect_to @todo, notice: "#{@todo.title} was successfully created."}
                format.json { render :show, status: :created, location: @user }
            else
                format.html { render :new, status: :unprocessable_entity }
                format.json { render json: @todo.errors, status: :unprocessable_entity }
            end
        end
    end

    def show
    end

    def edit
    end

    def update
        @todo.update(todo_params)
        respond_to do |format|
            if @todo.save
                format.html {redirect_to @todo, notice: "#{@todo.title} was successfully Updated."}
                format.json { render :show, status: :ok, location: @user }
            else
                format.html { render :edit, status: :unprocessable_entity }
                format.json { render json: @todo.errors, status: :unprocessable_entity }
            end
        end
    end

    def destroy
        @todo.destroy
        respond_to do |format|
            format.html { redirect_to root_path, notice: "User was successfully destroyed." }
            format.json { head :no_content }
        end
    end

    private

    def set_todo
        @todo = Todo.find(params[:id])
    end

    def todo_params
        params.require(:todo).permit(:count, :title, :description, :active)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

  </head>

  <body>
    <%= render partial: "shared/navbar"%>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light", style="margin-left: 20px">
    <div class="container">
        <%= link_to "To-Do", root_path, class: "navbar-brand" %>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <%= link_to "All Tasks", root_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Add New Task", new_todo_path, class: "nav-link"%>
                </li>
            </ul>
        </div>
    </div>
</nav>

app/views/todos/edit.html.erb
<section class="vh-100" style="background-color: #eee;">
  <% if notice %>
    <div class="alert alert-primary" role="alert">
      <%= notice %>
    </div>
  <% end %>
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-9 col-xl-7">
        <div class="card rounded-3">
          <div class="card-body p-4">

            <h4 class="text-center my-3 pb-3">To Do App</h4>
            <%= form_for(@todo) do |f| %>
                <% if @todo.errors.any? %>
                  <% @todo.errors.full_messages.each do |message| %>
                      <div class="alert alert-danger d-flex align-items-center" role="alert">
                          <div>
                            <%= message %>
                          </div>
                      </div>
                  <% end %>
                <% end %>
                <form class="row row-cols-lg-auto g-3 justify-content-center align-items-center mb-4 pb-2">
                <div class="col-12">
                    <div class="form-outline">
                    
                    <%= f.text_field :title, type: "text", class: "form-control", placeholder: "Enter title"%>
                    <br>
                    <%= f.text_area :description, type: "text", class: "form-control", placeholder: "Enter the Task"%>
                    <br>
                    <%= f.check_box :active, class: "form-check-input"%>
                    <%= f.label :completed %>
                    </div>
                </div>
                <br>
                <div class="col-6">
                    <%= f.submit "Update Task", class: "btn btn-primary" %>
                    <%= link_to 'Back', root_path, class: "btn btn-primary"%>
                </div>
                </form>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/todos/index.html.erb
<section class="vh-100" style="background-color: #eee;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-50">
      <div class="col col-lg-12 col-xl-12">
        <div class="card rounded-3">
          <div>
            <form style="margin-top: 40px">
              <h4 style="margin-left: 40px; margin-top: 40px">All taskes</h4>
                <div style="position: relative; left: 680px">
                    <span style="display: inline-block"><input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search"></span>
                    <span><button class="btn btn-outline-success", type="submit">Search</button></span>
                </div>
            </form>
            
          </div>
          <div class="card-body p-4">
            <%= link_to "Add New Task", new_todo_path, class: "btn btn-success"%>
            <br>
            <table class="table mb-4">
              <thead>
                <tr>
                  <th scope="col">Todo Title</th>
                  <th scope="col">Status</th>
                  <th scope="col">Actions</th>
                </tr>
              </thead>
              <tbody>
                <% @todo.each do |todo| %>
                    <tr>
                    <% if todo.active == true %>
                        <td><del><%= todo.title %></del></td>
                        <td><mark>Completed<mark></td>
                    <% else %>
                      <td><%= todo.title %></td>
                      <td>Not Completed</td>
                    <% end %>
                        <td>
                            <%= link_to 'Show', todo, class: "btn btn-success ms-1" %>
                            <%= link_to 'Edit', edit_todo_path(todo), class: "btn btn-success ms-1" %>
                            <span style="display: inline-block"><%= button_to "Delete", todo, class: "btn btn-danger",  method: :delete %></span>
                        </td>
                    </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/todos/new.html.erb
<section class="vh-100" style="background-color: #eee;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-9 col-xl-7">
        <div class="card rounded-3">
          <div class="card-body p-4">

            <h4 class="text-center my-3 pb-3">To Do App</h4>
            <%= form_for(@todo) do |form| %>
                  <% if @todo.errors.any? %>
                    <% @todo.errors.full_messages.each do |message| %>
                        <div class="alert alert-danger d-flex align-items-center" role="alert">
                            <div>
                              <%= message %>
                            </div>
                        </div>
                    <% end %>
                  <% end %>
                <form class="row row-cols-lg-auto g-3 justify-content-center align-items-center mb-4 pb-2">
                <div class="col-12">
                    <div class="form-outline">
                    
                    <%= form.text_field :title, type: "text", class: "form-control", placeholder: "Enter title"%>
                    <br>
                    <%= form.text_area :description, type: "text", class: "form-control", placeholder: "Enter the Task"%>
                    <br>
                    <%= form.check_box :active, class: "form-check-input"%>
                    <%= form.label :completed %>
                    </div>
                </div>
                <br>
                <div class="col-6">
                    <%= form.submit "Create Task", class: "btn btn-primary" %>
                    <%= link_to 'Back', root_path, class: "btn btn-primary"%>
                </div>
                </form>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/todos/show.html.erb
<section class="vh-100" style="background-color: #eee;">
  <% if notice %>
    <div class="alert alert-primary" role="alert">
      <%= notice %>
    </div>
  <% end %>
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-50">
      <div class="col col-lg-12 col-xl-12">
        <div class="card rounded-3"> 
          <div class="card-body p-4">
            <table class="table mb-4">
              <thead>
                <tr>
                  <th scope="col">Task Title</th>
                  <th scope="col">Status</th>
                  <th scope="col">Description</th>
                  <th scope="col">Actions</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                    <% if @todo.active == true %>
                        <td><del>@todo.title</del></td>
                        <td><mark>Completed<mark></td>
                    <% else %>
                      <td><%= @todo.title %></td>
                      <td>Not Completed</td>
                    <% end %>
                    <td style="min-width:40px; max-width:150px;"><%= @todo.description %></td>
                    <td>
                        <%= link_to 'Back', root_path, class: "btn btn-success ms-1" %>
                        <%= link_to 'Edit', edit_todo_path(@todo), class: "btn btn-success ms-1" %>
                        <span style="display: inline-block"><%= button_to "Delete", @todo, class: "btn btn-danger",  method: :delete %></span>
                    </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>